name: 自动部署到服务器测试
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
      - run: npm install
      - run: npm run build
      # 部署到服务器（此步骤待测试）
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v2.0.7
        # 注入环境变量供ssh-deploy使用
        env:
          # secrets中配置的私钥，用于免密连接服务器
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 服务器地址
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # 部署路径
          TARGET: ${{ secrets.TARGET }}
          # 打包文件来源
          SOURCE: "dist/"
          # 删除服务器上TARGET目录里所有文件
          ARGS: "-avz --delete"


      